### ISSUE TITLE
Official Review

### ISSUE THREAD

**Issue by micronet-challenge-submissions** [binhdt95/Jaist-MicroNet-Challenge#2]
Hello! We're trying to evaluate your entry and we're having trouble running your test.py script. When we do run it, we get an error from pickle when loading the checkpoint in your repo:

Traceback (most recent call last):
  File "test.py", line 63, in <module>
    model_load('WT103.12hr.QRNN.pt')
  File "test.py", line 58, in model_load
    model, criterion, optimizer = torch.load(f)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

We've tried it now on both python 3.7 and python 3.6 (with a couple of code changes to make it compatible) and we get the same error. Could you verify that you're able to run this checkpoint?

Trevor

**Comment by micronet-challenge-submissions** [comment]
Ah, it looks like I need git lfs to download it. Let me give that a try...

**Comment by micronet-challenge-submissions** [comment]
Hello,

We've completed evaluating your entry and everything checks out!

Trevor
